name: zego_uikit_prebuilt_call
description: PrebuiltCall is a full-featured call kit that provides a ready-made call invitation, voice/video chat, device detection, etc. Add a voice/video call to your app in minutes.
version: 3.6.2
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.5.22
  zego_plugin_adapter: ^2.3.1

  zego_zpns: 2.3.2+1

  http: ^0.13.4
  flutter_vibrate: ^1.3.0
  audioplayers: ^1.0.1
  statemachine: ^3.2.0
  uuid: ^3.0.7
  permission_handler: ^10.2.0
  #  1. make kotlin version >= 1.8.0, open the your_project/android/app/build.gradle file, and modify the kotlin_version to 1.8.0.
  #  2. make gradle version >= 7.0, open the your_project/android/gradle/wrapper/gradle-wrapper.properties file, and modify the distributionUrl to https\://services.gradle.org/distributions/gradle-7.0-all.zip.
  flutter_callkit_incoming: ^2.0.0
  awesome_notifications: ^0.7.5-dev.3

  shared_preferences:
  path_provider_android: "<=2.0.25"
  shared_preferences_android: "<=2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  assets:
    # call
    - assets/icons/

    # invitation
    - assets/invitation/audio/
    - assets/invitation/icons/
